/// Flutter icons NerdfontSymbols
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NerdfontSymbols
///      fonts:
///       - asset: fonts/NerdfontSymbols.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NerdfontSymbols {
  NerdfontSymbols._();

  static const _kFontFam = 'NerdfontSymbols';
  static const String? _kFontPkg = null;

  static const IconData fae_brain = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_brain = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seti_notebook = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_note_plus_outline = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_note_plus = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_note_multiple_outline = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_note_multiple = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_note = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dev_jetbrains = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_note_outline = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_tag = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_tag_outline = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dev_google = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dev_flutter = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_web = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData md_fire = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seti_firebase = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seti_html = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seti_less = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dev_twitter = IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cod_graph = IconData(0xeb03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cod_note = IconData(0xeb26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cod_notebook = IconData(0xebaf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cod_notebook_template = IconData(0xebbf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cod_graph_line = IconData(0xebe2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fa_notes_medical = IconData(0xed85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fa_jedi_order = IconData(0xedd8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fa_mandalorian = IconData(0xedd9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fa_old_republic = IconData(0xedda, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fa_brain = IconData(0xee9c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fa_google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fa_sticky_note = IconData(0xf249, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fa_sticky_note_o = IconData(0xf24a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linux_apple = IconData(0xf302, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oct_graph = IconData(0xf437, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oct_flame = IconData(0xf490, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
